# Generated by Django 4.0.4 on 2022-04-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('Username', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Degree', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('Username', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('CompanyName', models.CharField(max_length=50)),
                ('ImplicitBiasFile', models.CharField(max_length=500)),
            ],
        ),
    ]
